name: blurred
description: blurred - The easiest way to blur your flutter widgets and images.
version: 1.1.0
homepage: https://github.com/tusharsadhwani/blurred

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
